export type Borders = typeof borders;

export const borders = {
  transparent: `0.1rem solid transparent;`,
  default: `0.1rem solid var(--uxu-color-primary-accent3);`,
  active: `0.1rem solid var(--uxu-color-primary-foreground);`,
  primaryAccent2: `0.1rem solid var(--uxu-color-primary-accent2);`,
  primaryForeground: `0.1rem solid var(--uxu-color-primary-foreground);`,
  primaryBackground: `0.1rem solid var(--uxu-color-primary-background);`,
  successDefault: `0.1rem solid var(--uxu-color-success-default);`,
  errorDefault: `0.1rem solid var(--uxu-color-error-default);`,
  warningDefault: `0.1rem solid var(--uxu-color-warning-default);`,
  violetDefault: `0.1rem solid var(--uxu-color-violet-default);`,
  cyanDefault: `0.1rem solid var(--uxu-color-cyan-default);`,
  highlightPurple: `0.1rem solid var(--uxu-color-highlight-purple);`,
  highlightMagenta: `0.1rem solid var(--uxu-color-highlight-magenta);`,
  highlightPink: `0.1rem solid var(--uxu-color-highlight-pink);`,
  highlightYellow: `0.1rem solid var(--uxu-color-highlight-yellow);`,
  light100: `0.1rem solid rgba(var(--uxu-color-primary-foreground-rgba), 0.1);`,
  light200: `0.1rem solid rgba(var(--uxu-color-primary-foreground-rgba), 0.2);`,
  light300: `0.1rem solid rgba(var(--uxu-color-primary-foreground-rgba), 0.3);`,
  light400: `0.1rem solid rgba(var(--uxu-color-primary-foreground-rgba), 0.4);`,
  light500: `0.1rem solid rgba(var(--uxu-color-primary-foreground-rgba), 0.5);`,
  light600: `0.1rem solid rgba(var(--uxu-color-primary-foreground-rgba), 0.6);`,
  light700: `0.1rem solid rgba(var(--uxu-color-primary-foreground-rgba), 0.7);`,
  light800: `0.1rem solid rgba(var(--uxu-color-primary-foreground-rgba), 0.8);`,
  light900: `0.1rem solid rgba(var(--uxu-color-primary-foreground-rgba), 0.9);`,
  dark100: `0.1rem solid rgba(var(--uxu-color-primary-background-rgba), 0.1);`,
  dark200: `0.1rem solid rgba(var(--uxu-color-primary-background-rgba), 0.2);`,
  dark300: `0.1rem solid rgba(var(--uxu-color-primary-background-rgba), 0.3);`,
  dark400: `0.1rem solid rgba(var(--uxu-color-primary-background-rgba), 0.4);`,
  dark500: `0.1rem solid rgba(var(--uxu-color-primary-background-rgba), 0.5);`,
  dark600: `0.1rem solid rgba(var(--uxu-color-primary-background-rgba), 0.6);`,
  dark700: `0.1rem solid rgba(var(--uxu-color-primary-background-rgba), 0.7);`,
  dark800: `0.1rem solid rgba(var(--uxu-color-primary-background-rgba), 0.8);`,
  dark900: `0.1rem solid rgba(var(--uxu-color-primary-background-rgba), 0.9);`,
} as const;
